# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^src/synmetrix_python_client/graphql_client/
      - id: end-of-file-fixer
        exclude: ^src/synmetrix_python_client/graphql_client/
      - id: check-yaml
        exclude: ^src/synmetrix_python_client/graphql_client/
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: forbid-new-submodules

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args: [ --fix, --config=./ruff.toml ]
        exclude: ^src/synmetrix_python_client/graphql_client/
      - id: ruff-format
        exclude: ^src/synmetrix_python_client/graphql_client/

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.9
        exclude: ^src/synmetrix_python_client/graphql_client/
