# Generated by ariadne-codegen
# Source: src/synmetrix_graphql_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class RunSourceSQLQuery(BaseModel):
    run_query: Optional["RunSourceSQLQueryRunQuery"]


class RunSourceSQLQueryRunQuery(BaseModel):
    result: Optional[Any]


RunSourceSQLQuery.model_rebuild()
