# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class AccessList(BaseModel):
    access_lists_by_pk: Optional["AccessListAccessListsByPk"]


class AccessListAccessListsByPk(BaseModel):
    name: str
    config: Any
    team_id: Any


AccessList.model_rebuild()
