# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, List, Optional

from .base_model import BaseModel
from .enums import branch_statuses_enum


class AllDataSchemas(BaseModel):
    branches: List["AllDataSchemasBranches"]


class AllDataSchemasBranches(BaseModel):
    id: Any
    name: str
    status: branch_statuses_enum
    versions: List["AllDataSchemasBranchesVersions"]


class AllDataSchemasBranchesVersions(BaseModel):
    id: Any
    checksum: str
    created_at: Any
    updated_at: Any
    user: "AllDataSchemasBranchesVersionsUser"
    dataschemas: List["AllDataSchemasBranchesVersionsDataschemas"]


class AllDataSchemasBranchesVersionsUser(BaseModel):
    display_name: Optional[str]


class AllDataSchemasBranchesVersionsDataschemas(BaseModel):
    id: Any
    name: str
    code: str
    created_at: Any
    updated_at: Any
    datasource_id: Any


AllDataSchemas.model_rebuild()
AllDataSchemasBranches.model_rebuild()
AllDataSchemasBranchesVersions.model_rebuild()
