# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, List, Optional

from .base_model import BaseModel


class AllSchemas(BaseModel):
    dataschemas: List["AllSchemasDataschemas"]


class AllSchemasDataschemas(BaseModel):
    id: Any
    user_id: Any
    name: str
    checksum: Optional[str]
    datasource: "AllSchemasDataschemasDatasource"


class AllSchemasDataschemasDatasource(BaseModel):
    team_id: Optional[Any]


AllSchemas.model_rebuild()
AllSchemasDataschemas.model_rebuild()
