# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, List, Optional

from .base_model import BaseModel


class AllDataSources(BaseModel):
    datasources: List["AllDataSourcesDatasources"]


class AllDataSourcesDatasources(BaseModel):
    id: Any
    name: str
    db_params_computed: Optional[Any]
    db_type: str
    created_at: Any
    updated_at: Any
    branches: List["AllDataSourcesDatasourcesBranches"]
    sql_credentials: List["AllDataSourcesDatasourcesSqlCredentials"]


class AllDataSourcesDatasourcesBranches(BaseModel):
    id: Any


class AllDataSourcesDatasourcesSqlCredentials(BaseModel):
    id: Any
    username: str
    created_at: Any
    updated_at: Any
    user: "AllDataSourcesDatasourcesSqlCredentialsUser"


class AllDataSourcesDatasourcesSqlCredentialsUser(BaseModel):
    id: Any
    display_name: Optional[str]


AllDataSources.model_rebuild()
AllDataSourcesDatasources.model_rebuild()
AllDataSourcesDatasourcesSqlCredentials.model_rebuild()
