# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class CreateAlert(BaseModel):
    insert_alerts_one: Optional["CreateAlertInsertAlertsOne"]


class CreateAlertInsertAlertsOne(BaseModel):
    id: Any


CreateAlert.model_rebuild()
