# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, List, Optional

from .base_model import BaseModel


class CreateDataSource(BaseModel):
    insert_datasources_one: Optional["CreateDataSourceInsertDatasourcesOne"]


class CreateDataSourceInsertDatasourcesOne(BaseModel):
    id: Any
    name: str
    branches: List["CreateDataSourceInsertDatasourcesOneBranches"]
    sql_credentials: List["CreateDataSourceInsertDatasourcesOneSqlCredentials"]


class CreateDataSourceInsertDatasourcesOneBranches(BaseModel):
    id: Any


class CreateDataSourceInsertDatasourcesOneSqlCredentials(BaseModel):
    id: Any


CreateDataSource.model_rebuild()
CreateDataSourceInsertDatasourcesOne.model_rebuild()
