# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class CreateExploration(BaseModel):
    insert_explorations_one: Optional["CreateExplorationInsertExplorationsOne"]


class CreateExplorationInsertExplorationsOne(BaseModel):
    id: Any


CreateExploration.model_rebuild()
