# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class CreateTeam(BaseModel):
    create_team: Optional["CreateTeamCreateTeam"]


class CreateTeamCreateTeam(BaseModel):
    id: Optional[Any]
    name: Optional[str]


CreateTeam.model_rebuild()
