# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, List, Optional

from .base_model import BaseModel


class Credentials(BaseModel):
    sql_credentials: List["CredentialsSqlCredentials"]


class CredentialsSqlCredentials(BaseModel):
    id: Any
    username: str
    created_at: Any
    user: "CredentialsSqlCredentialsUser"
    datasource: "CredentialsSqlCredentialsDatasource"


class CredentialsSqlCredentialsUser(BaseModel):
    id: Any
    display_name: Optional[str]


class CredentialsSqlCredentialsDatasource(BaseModel):
    id: Any
    name: str
    db_type: str
    db_params_computed: Optional[Any]


Credentials.model_rebuild()
CredentialsSqlCredentials.model_rebuild()
