# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, List, Optional

from .base_model import BaseModel


class CurrentVersion(BaseModel):
    versions: List["CurrentVersionVersions"]


class CurrentVersionVersions(BaseModel):
    id: Any
    checksum: str
    dataschemas: List["CurrentVersionVersionsDataschemas"]


class CurrentVersionVersionsDataschemas(BaseModel):
    created_at: Any
    updated_at: Any
    datasource_id: Any
    id: Any
    user_id: Any
    name: str
    code: str
    checksum: Optional[str]


CurrentVersion.model_rebuild()
CurrentVersionVersions.model_rebuild()
