# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class CurrentExploration(BaseModel):
    explorations_by_pk: Optional["CurrentExplorationExplorationsByPk"]
    fetch_dataset: Optional["CurrentExplorationFetchDataset"]


class CurrentExplorationExplorationsByPk(BaseModel):
    id: Any
    branch_id: Optional[Any]
    datasource_id: Any
    playground_state: Any
    playground_settings: Any
    created_at: Any
    updated_at: Any


class CurrentExplorationFetchDataset(BaseModel):
    annotation: Optional[Any]
    data: Optional[Any]
    query: Optional[Any]
    progress: Optional[Any]
    hit_limit: Optional[bool] = Field(alias="hitLimit")


CurrentExploration.model_rebuild()
