# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, List, Optional

from .base_model import BaseModel


class CurrentTeam(BaseModel):
    teams_by_pk: Optional["CurrentTeamTeamsByPk"]


class CurrentTeamTeamsByPk(BaseModel):
    id: Any
    created_at: Any
    updated_at: Any
    members: List["CurrentTeamTeamsByPkMembers"]


class CurrentTeamTeamsByPkMembers(BaseModel):
    user: "CurrentTeamTeamsByPkMembersUser"


class CurrentTeamTeamsByPkMembersUser(BaseModel):
    display_name: Optional[str]


CurrentTeam.model_rebuild()
CurrentTeamTeamsByPk.model_rebuild()
CurrentTeamTeamsByPkMembers.model_rebuild()
