# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import DefaultFields


class CurrentLog(BaseModel):
    request_logs_by_pk: Optional["CurrentLogRequestLogsByPk"]


class CurrentLogRequestLogsByPk(DefaultFields):
    end_time: Any
    request_id: str
    updated_at: Any
    request_event_logs: List["CurrentLogRequestLogsByPkRequestEventLogs"]


class CurrentLogRequestLogsByPkRequestEventLogs(BaseModel):
    id: Any
    duration: Optional[Any]
    event: str
    path: Optional[str]
    query: Optional[Any]
    query_key: Optional[Any]
    query_sql: Optional[str]
    query_key_md_5: Optional[str] = Field(alias="query_key_md5")
    queue_prefix: Optional[str]
    time_in_queue: Optional[Any]
    timestamp: Optional[Any]
    error: Optional[str]


CurrentLog.model_rebuild()
CurrentLogRequestLogsByPk.model_rebuild()
