# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class CurrentDataSource(BaseModel):
    datasources_by_pk: Optional["CurrentDataSourceDatasourcesByPk"]


class CurrentDataSourceDatasourcesByPk(BaseModel):
    id: Any
    name: str
    db_type: str
    db_params_computed: Optional[Any]
    created_at: Any
    updated_at: Any


CurrentDataSource.model_rebuild()
