# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, List, Optional

from .base_model import BaseModel
from .enums import team_roles_enum
from .fragments import UserTeamFields


class CurrentUser(BaseModel):
    users_by_pk: Optional["CurrentUserUsersByPk"]


class CurrentUserUsersByPk(BaseModel):
    id: Any
    display_name: Optional[str]
    avatar_url: Optional[str]
    account: Optional["CurrentUserUsersByPkAccount"]
    members: List["CurrentUserUsersByPkMembers"]


class CurrentUserUsersByPkAccount(BaseModel):
    email: Optional[Any]


class CurrentUserUsersByPkMembers(BaseModel):
    member_roles: List["CurrentUserUsersByPkMembersMemberRoles"]
    user: "CurrentUserUsersByPkMembersUser"
    team: "CurrentUserUsersByPkMembersTeam"


class CurrentUserUsersByPkMembersMemberRoles(BaseModel):
    team_role: team_roles_enum


class CurrentUserUsersByPkMembersUser(BaseModel):
    id: Any
    avatar_url: Optional[str]
    display_name: Optional[str]
    account: Optional["CurrentUserUsersByPkMembersUserAccount"]


class CurrentUserUsersByPkMembersUserAccount(BaseModel):
    email: Optional[Any]


class CurrentUserUsersByPkMembersTeam(UserTeamFields):
    pass


CurrentUser.model_rebuild()
CurrentUserUsersByPk.model_rebuild()
CurrentUserUsersByPkMembers.model_rebuild()
CurrentUserUsersByPkMembersUser.model_rebuild()
