# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class DeleteBranch(BaseModel):
    update_branches_by_pk: Optional["DeleteBranchUpdateBranchesByPk"]


class DeleteBranchUpdateBranchesByPk(BaseModel):
    id: Any


DeleteBranch.model_rebuild()
