# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class DeleteMember(BaseModel):
    delete_members_by_pk: Optional["DeleteMemberDeleteMembersByPk"]


class DeleteMemberDeleteMembersByPk(BaseModel):
    id: Any


DeleteMember.model_rebuild()
