# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class DeleteDataSource(BaseModel):
    delete_datasources_by_pk: Optional["DeleteDataSourceDeleteDatasourcesByPk"]


class DeleteDataSourceDeleteDatasourcesByPk(BaseModel):
    id: Any


DeleteDataSource.model_rebuild()
