# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class DeleteAlert(BaseModel):
    delete_alerts_by_pk: Optional["DeleteAlertDeleteAlertsByPk"]


class DeleteAlertDeleteAlertsByPk(BaseModel):
    id: Any


DeleteAlert.model_rebuild()
