# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class DeleteSchema(BaseModel):
    update_branches_by_pk: Optional["DeleteSchemaUpdateBranchesByPk"]


class DeleteSchemaUpdateBranchesByPk(BaseModel):
    id: Any


DeleteSchema.model_rebuild()
