# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class DeleteAccessList(BaseModel):
    delete_access_lists_by_pk: Optional["DeleteAccessListDeleteAccessListsByPk"]


class DeleteAccessListDeleteAccessListsByPk(BaseModel):
    id: Any


DeleteAccessList.model_rebuild()
