# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class DeleteTeam(BaseModel):
    delete_teams_by_pk: Optional["DeleteTeamDeleteTeamsByPk"]


class DeleteTeamDeleteTeamsByPk(BaseModel):
    id: Any


DeleteTeam.model_rebuild()
