# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class EditTeam(BaseModel):
    update_teams_by_pk: Optional["EditTeamUpdateTeamsByPk"]


class EditTeamUpdateTeamsByPk(BaseModel):
    id: Any
    name: str


EditTeam.model_rebuild()
