# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Optional

from .base_model import BaseModel


class ExportData(BaseModel):
    export_data_models: Optional["ExportDataExportDataModels"]


class ExportDataExportDataModels(BaseModel):
    download_url: str


ExportData.model_rebuild()
