# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class FetchTables(BaseModel):
    fetch_tables: Optional["FetchTablesFetchTables"]


class FetchTablesFetchTables(BaseModel):
    schema_: Optional[Any] = Field(alias="schema")


FetchTables.model_rebuild()
