# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class FetchMeta(BaseModel):
    fetch_meta: Optional["FetchMetaFetchMeta"]


class FetchMetaFetchMeta(BaseModel):
    cubes: Optional[Any]


FetchMeta.model_rebuild()
