# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, List, Optional

from .base_model import BaseModel
from .enums import branch_statuses_enum, team_roles_enum


class BranchesFields(BaseModel):
    id: Any
    name: str
    status: branch_statuses_enum


class DefaultFields(BaseModel):
    id: Any
    created_at: Any
    start_time: Any
    duration: Optional[Any]
    path: Optional[str]
    user_id: Any
    datasource_id: Any


class TeamMembersFields(BaseModel):
    members: List["TeamMembersFieldsMembers"]


class TeamMembersFieldsMembers(BaseModel):
    id: Any
    user_id: Any
    member_roles: List["TeamMembersFieldsMembersMemberRoles"]
    user: "TeamMembersFieldsMembersUser"


class TeamMembersFieldsMembersMemberRoles(BaseModel):
    id: Any
    team_role: team_roles_enum
    created_at: Optional[Any]
    updated_at: Optional[Any]
    access_list: Optional["TeamMembersFieldsMembersMemberRolesAccessList"]


class TeamMembersFieldsMembersMemberRolesAccessList(BaseModel):
    id: Any
    name: str
    config: Any


class TeamMembersFieldsMembersUser(BaseModel):
    id: Any
    avatar_url: Optional[str]
    display_name: Optional[str]
    account: Optional["TeamMembersFieldsMembersUserAccount"]


class TeamMembersFieldsMembersUserAccount(BaseModel):
    email: Optional[Any]


class UserTeamFields(BaseModel):
    id: Any
    name: str
    created_at: Any
    updated_at: Any
    members: List["UserTeamFieldsMembers"]


class UserTeamFieldsMembers(BaseModel):
    id: Any
    user_id: Any
    member_roles: List["UserTeamFieldsMembersMemberRoles"]
    user: "UserTeamFieldsMembersUser"


class UserTeamFieldsMembersMemberRoles(BaseModel):
    team_role: team_roles_enum


class UserTeamFieldsMembersUser(BaseModel):
    id: Any
    avatar_url: Optional[str]
    display_name: Optional[str]
    account: Optional["UserTeamFieldsMembersUserAccount"]


class UserTeamFieldsMembersUserAccount(BaseModel):
    email: Optional[Any]


BranchesFields.model_rebuild()
DefaultFields.model_rebuild()
TeamMembersFields.model_rebuild()
UserTeamFields.model_rebuild()
