# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class GenSQL(BaseModel):
    gen_sql: Optional["GenSQLGenSql"]


class GenSQLGenSql(BaseModel):
    result: Optional[Any]


GenSQL.model_rebuild()
