# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, List

from .base_model import BaseModel


class GetUsers(BaseModel):
    users: List["GetUsersUsers"]


class GetUsersUsers(BaseModel):
    id: Any


GetUsers.model_rebuild()
