# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class InsertSqlCredentials(BaseModel):
    insert_sql_credentials_one: Optional["InsertSqlCredentialsInsertSqlCredentialsOne"]


class InsertSqlCredentialsInsertSqlCredentialsOne(BaseModel):
    id: Any


InsertSqlCredentials.model_rebuild()
