# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class InviteMember(BaseModel):
    invite_team_member: Optional["InviteMemberInviteTeamMember"]


class InviteMemberInviteTeamMember(BaseModel):
    member_id: Optional[Any] = Field(alias="memberId")


InviteMember.model_rebuild()
