# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, List, Optional

from .base_model import BaseModel
from .enums import team_roles_enum


class Members(BaseModel):
    members: List["MembersMembers"]


class MembersMembers(BaseModel):
    id: Any
    user: "MembersMembersUser"
    member_roles: List["MembersMembersMemberRoles"]
    updated_at: Any
    created_at: Any


class MembersMembersUser(BaseModel):
    id: Any
    display_name: Optional[str]
    account: Optional["MembersMembersUserAccount"]


class MembersMembersUserAccount(BaseModel):
    email: Optional[Any]


class MembersMembersMemberRoles(BaseModel):
    id: Any
    team_role: team_roles_enum
    access_list: Optional["MembersMembersMemberRolesAccessList"]
    updated_at: Optional[Any]
    created_at: Optional[Any]


class MembersMembersMemberRolesAccessList(BaseModel):
    id: Any
    name: str


Members.model_rebuild()
MembersMembers.model_rebuild()
MembersMembersUser.model_rebuild()
MembersMembersMemberRoles.model_rebuild()
