# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class SendTestAlert(BaseModel):
    send_test_alert: Optional["SendTestAlertSendTestAlert"]


class SendTestAlertSendTestAlert(BaseModel):
    error: Optional[bool]
    result: Optional[Any]


SendTestAlert.model_rebuild()
