# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class SetDefaultBranch(BaseModel):
    update_branches: Optional["SetDefaultBranchUpdateBranches"]
    update_branches_by_pk: Optional["SetDefaultBranchUpdateBranchesByPk"]


class SetDefaultBranchUpdateBranches(BaseModel):
    affected_rows: int


class SetDefaultBranchUpdateBranchesByPk(BaseModel):
    id: Any
    name: str


SetDefaultBranch.model_rebuild()
