# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, List, Optional

from .base_model import BaseModel
from .enums import team_roles_enum
from .fragments import UserTeamFields


class SubCurrentUser(BaseModel):
    users_by_pk: Optional["SubCurrentUserUsersByPk"]


class SubCurrentUserUsersByPk(BaseModel):
    id: Any
    display_name: Optional[str]
    avatar_url: Optional[str]
    account: Optional["SubCurrentUserUsersByPkAccount"]
    members: List["SubCurrentUserUsersByPkMembers"]


class SubCurrentUserUsersByPkAccount(BaseModel):
    email: Optional[Any]


class SubCurrentUserUsersByPkMembers(BaseModel):
    id: Any
    user_id: Any
    member_roles: List["SubCurrentUserUsersByPkMembersMemberRoles"]
    user: "SubCurrentUserUsersByPkMembersUser"
    team: "SubCurrentUserUsersByPkMembersTeam"


class SubCurrentUserUsersByPkMembersMemberRoles(BaseModel):
    id: Any
    team_role: team_roles_enum
    created_at: Optional[Any]
    updated_at: Optional[Any]
    access_list: Optional["SubCurrentUserUsersByPkMembersMemberRolesAccessList"]


class SubCurrentUserUsersByPkMembersMemberRolesAccessList(BaseModel):
    id: Any
    name: str
    config: Any


class SubCurrentUserUsersByPkMembersUser(BaseModel):
    id: Any
    avatar_url: Optional[str]
    display_name: Optional[str]
    account: Optional["SubCurrentUserUsersByPkMembersUserAccount"]


class SubCurrentUserUsersByPkMembersUserAccount(BaseModel):
    email: Optional[Any]


class SubCurrentUserUsersByPkMembersTeam(UserTeamFields):
    pass


SubCurrentUser.model_rebuild()
SubCurrentUserUsersByPk.model_rebuild()
SubCurrentUserUsersByPkMembers.model_rebuild()
SubCurrentUserUsersByPkMembersMemberRoles.model_rebuild()
SubCurrentUserUsersByPkMembersUser.model_rebuild()
