# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, List

from .base_model import BaseModel


class SubCredentials(BaseModel):
    sql_credentials: List["SubCredentialsSqlCredentials"]


class SubCredentialsSqlCredentials(BaseModel):
    id: Any


SubCredentials.model_rebuild()
