# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, List

from .base_model import BaseModel


class SubAllLogs(BaseModel):
    request_logs: List["SubAllLogsRequestLogs"]


class SubAllLogsRequestLogs(BaseModel):
    id: Any


SubAllLogs.model_rebuild()
