# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, List

from .base_model import BaseModel


class SubAccessLists(BaseModel):
    access_lists: List["SubAccessListsAccessLists"]


class SubAccessListsAccessLists(BaseModel):
    id: Any
    name: str
    config: Any
    created_at: Any
    updated_at: Any


SubAccessLists.model_rebuild()
