# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, List, Optional

from .base_model import BaseModel
from .fragments import BranchesFields, TeamMembersFields


class SubTeamData(BaseModel):
    teams_by_pk: Optional["SubTeamDataTeamsByPk"]


class SubTeamDataTeamsByPk(TeamMembersFields):
    datasources: List["SubTeamDataTeamsByPkDatasources"]
    alerts: List["SubTeamDataTeamsByPkAlerts"]
    reports: List["SubTeamDataTeamsByPkReports"]


class SubTeamDataTeamsByPkDatasources(BaseModel):
    id: Any
    name: str
    db_params_computed: Optional[Any]
    db_type: str
    created_at: Any
    updated_at: Any
    branches: List["SubTeamDataTeamsByPkDatasourcesBranches"]
    sql_credentials: List["SubTeamDataTeamsByPkDatasourcesSqlCredentials"]


class SubTeamDataTeamsByPkDatasourcesBranches(BranchesFields):
    pass


class SubTeamDataTeamsByPkDatasourcesSqlCredentials(BaseModel):
    id: Any
    username: str
    created_at: Any
    updated_at: Any
    user: "SubTeamDataTeamsByPkDatasourcesSqlCredentialsUser"


class SubTeamDataTeamsByPkDatasourcesSqlCredentialsUser(BaseModel):
    id: Any
    display_name: Optional[str]


class SubTeamDataTeamsByPkAlerts(BaseModel):
    id: Any
    name: str
    delivery_type: str
    delivery_config: Any
    trigger_config: Any
    created_at: Any
    updated_at: Any
    schedule: str
    user: "SubTeamDataTeamsByPkAlertsUser"
    exploration: "SubTeamDataTeamsByPkAlertsExploration"


class SubTeamDataTeamsByPkAlertsUser(BaseModel):
    id: Any
    avatar_url: Optional[str]
    display_name: Optional[str]
    account: Optional["SubTeamDataTeamsByPkAlertsUserAccount"]


class SubTeamDataTeamsByPkAlertsUserAccount(BaseModel):
    email: Optional[Any]


class SubTeamDataTeamsByPkAlertsExploration(BaseModel):
    id: Any
    playground_state: Any


class SubTeamDataTeamsByPkReports(BaseModel):
    id: Any
    name: str
    schedule: str
    delivery_type: str
    delivery_config: Any
    created_at: Any
    updated_at: Any
    user: "SubTeamDataTeamsByPkReportsUser"
    exploration: "SubTeamDataTeamsByPkReportsExploration"


class SubTeamDataTeamsByPkReportsUser(BaseModel):
    id: Any
    avatar_url: Optional[str]
    display_name: Optional[str]
    account: Optional["SubTeamDataTeamsByPkReportsUserAccount"]


class SubTeamDataTeamsByPkReportsUserAccount(BaseModel):
    email: Optional[Any]


class SubTeamDataTeamsByPkReportsExploration(BaseModel):
    id: Any
    playground_state: Any


SubTeamData.model_rebuild()
SubTeamDataTeamsByPk.model_rebuild()
SubTeamDataTeamsByPkDatasources.model_rebuild()
SubTeamDataTeamsByPkDatasourcesSqlCredentials.model_rebuild()
SubTeamDataTeamsByPkAlerts.model_rebuild()
SubTeamDataTeamsByPkAlertsUser.model_rebuild()
SubTeamDataTeamsByPkReports.model_rebuild()
SubTeamDataTeamsByPkReportsUser.model_rebuild()
