# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, List, Optional

from .base_model import BaseModel
from .fragments import BranchesFields, TeamMembersFields


class TeamData(BaseModel):
    teams_by_pk: Optional["TeamDataTeamsByPk"]


class TeamDataTeamsByPk(TeamMembersFields):
    datasources: List["TeamDataTeamsByPkDatasources"]
    alerts: List["TeamDataTeamsByPkAlerts"]
    reports: List["TeamDataTeamsByPkReports"]


class TeamDataTeamsByPkDatasources(BaseModel):
    id: Any
    name: str
    db_params_computed: Optional[Any]
    db_type: str
    created_at: Any
    updated_at: Any
    branches: List["TeamDataTeamsByPkDatasourcesBranches"]
    sql_credentials: List["TeamDataTeamsByPkDatasourcesSqlCredentials"]


class TeamDataTeamsByPkDatasourcesBranches(BranchesFields):
    pass


class TeamDataTeamsByPkDatasourcesSqlCredentials(BaseModel):
    id: Any
    username: str
    created_at: Any
    updated_at: Any
    user: "TeamDataTeamsByPkDatasourcesSqlCredentialsUser"


class TeamDataTeamsByPkDatasourcesSqlCredentialsUser(BaseModel):
    id: Any
    display_name: Optional[str]


class TeamDataTeamsByPkAlerts(BaseModel):
    id: Any
    name: str
    delivery_type: str
    delivery_config: Any
    trigger_config: Any
    created_at: Any
    updated_at: Any
    schedule: str
    user: "TeamDataTeamsByPkAlertsUser"
    exploration: "TeamDataTeamsByPkAlertsExploration"


class TeamDataTeamsByPkAlertsUser(BaseModel):
    id: Any
    avatar_url: Optional[str]
    display_name: Optional[str]
    account: Optional["TeamDataTeamsByPkAlertsUserAccount"]


class TeamDataTeamsByPkAlertsUserAccount(BaseModel):
    email: Optional[Any]


class TeamDataTeamsByPkAlertsExploration(BaseModel):
    id: Any
    playground_state: Any


class TeamDataTeamsByPkReports(BaseModel):
    id: Any
    name: str
    schedule: str
    delivery_type: str
    delivery_config: Any
    created_at: Any
    updated_at: Any
    user: "TeamDataTeamsByPkReportsUser"
    exploration: "TeamDataTeamsByPkReportsExploration"


class TeamDataTeamsByPkReportsUser(BaseModel):
    id: Any
    avatar_url: Optional[str]
    display_name: Optional[str]
    account: Optional["TeamDataTeamsByPkReportsUserAccount"]


class TeamDataTeamsByPkReportsUserAccount(BaseModel):
    email: Optional[Any]


class TeamDataTeamsByPkReportsExploration(BaseModel):
    id: Any
    playground_state: Any


TeamData.model_rebuild()
TeamDataTeamsByPk.model_rebuild()
TeamDataTeamsByPkDatasources.model_rebuild()
TeamDataTeamsByPkDatasourcesSqlCredentials.model_rebuild()
TeamDataTeamsByPkAlerts.model_rebuild()
TeamDataTeamsByPkAlertsUser.model_rebuild()
TeamDataTeamsByPkReports.model_rebuild()
TeamDataTeamsByPkReportsUser.model_rebuild()
