# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class UpdateAccessList(BaseModel):
    update_access_lists_by_pk: Optional["UpdateAccessListUpdateAccessListsByPk"]


class UpdateAccessListUpdateAccessListsByPk(BaseModel):
    id: Any


UpdateAccessList.model_rebuild()
