# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class UpdateMemberRole(BaseModel):
    update_member_roles_by_pk: Optional["UpdateMemberRoleUpdateMemberRolesByPk"]


class UpdateMemberRoleUpdateMemberRolesByPk(BaseModel):
    id: Any


UpdateMemberRole.model_rebuild()
