# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class UpdateUserInfo(BaseModel):
    update_users_by_pk: Optional["UpdateUserInfoUpdateUsersByPk"]
    update_auth_accounts: Optional["UpdateUserInfoUpdateAuthAccounts"]


class UpdateUserInfoUpdateUsersByPk(BaseModel):
    id: Any


class UpdateUserInfoUpdateAuthAccounts(BaseModel):
    affected_rows: int


UpdateUserInfo.model_rebuild()
