# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class UpdateReport(BaseModel):
    update_reports_by_pk: Optional["UpdateReportUpdateReportsByPk"]


class UpdateReportUpdateReportsByPk(BaseModel):
    id: Any


UpdateReport.model_rebuild()
