# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class UpdateMember(BaseModel):
    update_members_by_pk: Optional["UpdateMemberUpdateMembersByPk"]


class UpdateMemberUpdateMembersByPk(BaseModel):
    id: Any


UpdateMember.model_rebuild()
