# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, List, Optional

from .base_model import BaseModel


class UpdateDataSource(BaseModel):
    update_datasources_by_pk: Optional["UpdateDataSourceUpdateDatasourcesByPk"]


class UpdateDataSourceUpdateDatasourcesByPk(BaseModel):
    id: Any
    branches: List["UpdateDataSourceUpdateDatasourcesByPkBranches"]


class UpdateDataSourceUpdateDatasourcesByPkBranches(BaseModel):
    id: Any


UpdateDataSource.model_rebuild()
UpdateDataSourceUpdateDatasourcesByPk.model_rebuild()
