# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class UpdateAlert(BaseModel):
    update_alerts_by_pk: Optional["UpdateAlertUpdateAlertsByPk"]


class UpdateAlertUpdateAlertsByPk(BaseModel):
    id: Any


UpdateAlert.model_rebuild()
