# Generated by ariadne-codegen
# Source: src/synmetrix_python_client/graphql

from typing import Optional

from .base_model import BaseModel


class VersionsCount(BaseModel):
    versions_aggregate: "VersionsCountVersionsAggregate"


class VersionsCountVersionsAggregate(BaseModel):
    aggregate: Optional["VersionsCountVersionsAggregateAggregate"]


class VersionsCountVersionsAggregateAggregate(BaseModel):
    count: int


VersionsCount.model_rebuild()
VersionsCountVersionsAggregate.model_rebuild()
