# Generated by ariadne-codegen
# Source: synmetrix_graphql_client/graphql

from typing import Any, List

from .base_model import BaseModel


class AllAccessLists(BaseModel):
    access_lists: List["AllAccessListsAccessLists"]


class AllAccessListsAccessLists(BaseModel):
    id: Any
    name: str
    config: Any
    team_id: Any
    created_at: Any
    updated_at: Any


AllAccessLists.model_rebuild()
