# Generated by ariadne-codegen
# Source: synmetrix_graphql_client/graphql

from typing import Optional

from .base_model import BaseModel


class CheckConnection(BaseModel):
    check_connection: Optional["CheckConnectionCheckConnection"]


class CheckConnectionCheckConnection(BaseModel):
    message: Optional[str]
    code: str


CheckConnection.model_rebuild()
