# Generated by ariadne-codegen
# Source: synmetrix_graphql_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class CreateAccessList(BaseModel):
    insert_access_lists_one: Optional["CreateAccessListInsertAccessListsOne"]


class CreateAccessListInsertAccessListsOne(BaseModel):
    id: Any


CreateAccessList.model_rebuild()
