# Generated by ariadne-codegen
# Source: synmetrix_graphql_client/graphql

from typing import Any, Optional

from .base_model import BaseModel


class DeleteReport(BaseModel):
    delete_reports_by_pk: Optional["DeleteReportDeleteReportsByPk"]


class DeleteReportDeleteReportsByPk(BaseModel):
    id: Any


DeleteReport.model_rebuild()
