# Generated by ariadne-codegen
# Source: synmetrix_graphql_client/graphql

from typing import Optional

from .base_model import BaseModel


class VersionDoc(BaseModel):
    versions_by_pk: Optional["VersionDocVersionsByPk"]


class VersionDocVersionsByPk(BaseModel):
    markdown_doc: Optional[str]


VersionDoc.model_rebuild()
