query Credentials($teamId: uuid!) {
  sql_credentials(
    where: { datasource: { team_id: { _eq: $teamId } } }
    order_by: { created_at: desc }
  ) {
    id
    username
    created_at
    user {
      id
      display_name
    }
    datasource {
      id
      name
      db_type
      db_params_computed
    }
  }
}

subscription SubCredentials($teamId: uuid!) {
  sql_credentials(where: { datasource: { team_id: { _eq: $teamId } } }) {
    id
  }
}

mutation InsertSqlCredentials($object: sql_credentials_insert_input!) {
  insert_sql_credentials_one(object: $object) {
    id
  }
}

mutation DeleteCredentials($id: uuid!) {
  delete_sql_credentials_by_pk(id: $id) {
    id
  }
}
